spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:33306/beer_game
    username: root
    password:
  thymeleaf:
    mode: HTML5
    cache: false

mybatis:
  configuration:
    useColumnLabel: true
    mapUnderscoreToCamelCase: true
  mapper-locations: mybatis/mapper/*.xml
